version: "3.9"
services:
  crawler:
    build: .
    env_file:
      - .env
    # to run hot or train: override command
    # command: ["python", "crawler_unified.py", "--mode", "hot"]
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: {}
